services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: cars_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: