services:
  db: 
    container_name: psql_db
    image: postgres:16-alpine 
    restart: always 
    environment:
      POSTGRES_DB: ${DB_NAME} 
      POSTGRES_USER: ${DB_USER}        
      POSTGRES_PASSWORD: ${DB_PASSWORD} 
    ports:
      - "5432:5432"
    networks:
      - mcp-net
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d

volumes:
  db_data: 

networks:
  mcp-net:
    external: true